(() => {
const DATA = window.BET_TRACKER_DATA;
if (!DATA) return;
const CFG = DATA.config;
const unit = CFG.unitDollars;
const cap = CFG.weeklyCapUnits;
const state = {scores:{},overrides:JSON.parse(localStorage.getItem('football-score-overrides')||'{}'),selectedWeeks:{},filters:{NCAA:'all',NFL:'all'},lastRefresh:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`${n<0?'-':''}$${Math.abs(Number(n)||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const unitFmt=n=>`${((Number(n)||0)/unit).toFixed(2)}u`;
const pct=n=>`${(Number(n)||0).toFixed(1)}%`;
const signed=n=>`${n>0?'+':''}${Number(n).toFixed(1)}`;
const ymd=s=>String(s).replaceAll('-','');
const normalize=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const aliases={'san jose state':['sanjosestate','sanjosest','sjsu'],'eastern michigan':['easternmichigan','emichigan','emu'],'washington state':['washingtonstate','washingtonst','wsu'],'washington':['washington','wash','uw'],'western michigan':['westernmichigan','wmichigan','wmu'],'michigan':['michigan','mich'],'western kentucky':['westernkentucky','westernky','wku'],'florida atlantic':['floridaatlantic','fau'],'michigan state':['michiganstate','michiganst','msu'],'colorado state':['coloradostate','coloradost','csu'],'east carolina':['eastcarolina','ecu'],'notre dame':['notredame','nd'],'oklahoma state':['oklahomastate','oklahomast','okstate','okst'],'tulane':['tulane','tuln'],'duke':['duke'],'alabama':['alabama','ala'],'auburn':['auburn','aub'],'baylor':['baylor','bay'],'wisconsin':['wisconsin','wis'],'wyoming':['wyoming','wyo'],'toledo':['toledo','tol'],'nevada':['nevada','nev'],'tulsa':['tulsa','tlsa'],'florida':['florida','fla']};
const variantsFor=input=>{const key=String(input||'').toLowerCase();return [...new Set([normalize(input),...(aliases[key]||[]).map(normalize)].filter(Boolean))]};
const exactTeamMatch=(input,candidate)=>variantsFor(input).includes(normalize(candidate));
function formatTime(iso){if(!iso)return'TBD';try{return new Intl.DateTimeFormat('en-US',{timeZone:CFG.timezone,weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(iso))+` ${CFG.timezoneLabel}`}catch{return'TBD'}}
function formatStamp(iso){if(!iso)return'—';try{return new Intl.DateTimeFormat('en-US',{timeZone:CFG.timezone,month:'short',day:'numeric',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(iso))+` ${CFG.timezoneLabel}`}catch{return'—'}}
function extractEvent(ev){const comp=ev?.competitions?.[0];if(!comp)return null;const teams=(comp.competitors||[]).map(c=>({name:c.team?.displayName||c.team?.shortDisplayName||'',short:c.team?.shortDisplayName||'',abbr:c.team?.abbreviation||'',score:Number(c.score||0),home:c.homeAway==='home'}));if(teams.length<2)return null;const st=comp.status?.type||ev.status?.type||{};return{id:String(ev.id||''),name:ev.name||'',teams,status:st.completed?'final':(st.state==='in'?'live':'scheduled'),detail:st.shortDetail||st.detail||'',date:ev.date}}
function eventMatchesLeg(ev,leg){if(!ev||!leg)return false;if(leg.espnEventId&&String(ev.id)===String(leg.espnEventId))return true;const hits=name=>ev.teams.map((t,i)=>({i,ok:[t.name,t.short,t.abbr].some(v=>exactTeamMatch(name,v))})).filter(x=>x.ok);const a=hits(leg.team),b=hits(leg.opponent);return a.length===1&&b.length===1&&a[0].i!==b[0].i}
function findScore(leg,leagueKey){const override=state.overrides[leg.gameKey];if(override)return override;const events=state.scores[leagueKey]||[];if(leg.espnEventId){const byId=events.find(ev=>String(ev.id)===String(leg.espnEventId));if(byId)return byId}return events.find(ev=>eventMatchesLeg(ev,leg))||null}
function teamIndex(ev,name){if(!ev?.teams)return-1;const matches=ev.teams.map((t,i)=>({i,ok:[t.name,t.short,t.abbr].some(v=>exactTeamMatch(name,v))})).filter(x=>x.ok);return matches.length===1?matches[0].i:-1}
function legSnapshot(leg,leagueKey){const ev=findScore(leg,leagueKey);if(!ev)return{status:'open',label:'Awaiting score',event:null,edge:null,scoreText:'No score yet'};const ti=teamIndex(ev,leg.team),oi=teamIndex(ev,leg.opponent);if(ti<0||oi<0||ti===oi)return{status:'open',label:'Awaiting matchup',event:ev,edge:null,scoreText:ev.detail||'Scheduled'};const ts=ev.teams[ti].score,os=ev.teams[oi].score,total=ts+os;let edge=0;if(leg.betType==='spread')edge=ts+Number(leg.line||0)-os;else if(leg.betType==='moneyline')edge=ts-os;else if(leg.betType==='total')edge=leg.direction==='under'?Number(leg.line)-total:total-Number(leg.line);const scoreText=`${ev.teams[ti].abbr||leg.team} ${ts} · ${ev.teams[oi].abbr||leg.opponent} ${os}${ev.detail?' · '+ev.detail:''}`;if(ev.status==='scheduled')return{status:'open',label:formatTime(ev.date),event:ev,edge:null,scoreText};if(ev.status==='live'){const label=edge>0?`Winning by ${Math.abs(edge).toFixed(edge%1?1:0)}`:edge<0?`Behind by ${Math.abs(edge).toFixed(Math.abs(edge)%1?1:0)}`:'Currently push';return{status:'live',label,event:ev,edge,scoreText}}const result=edge>0?'win':edge<0?'loss':'push';return{status:result,label:result.toUpperCase(),event:ev,edge,scoreText}}
function ticketSnapshot(ticket,leagueKey){if(ticket.pass)return{status:'pass',result:'pass',pnl:0,legs:[],detail:'Intentional pass'};if(!ticket.booked)return{status:'planned',result:null,pnl:0,legs:[],detail:'Not booked yet'};if(ticket.result){const result=String(ticket.result).toLowerCase();const pnl=Number.isFinite(Number(ticket.pnl))?Number(ticket.pnl):(result==='win'?ticket.toWin:result==='loss'?-ticket.risk:0);return{status:result,result,pnl,legs:[],detail:'Archived result'}}const legs=(ticket.legs||[]).map(l=>legSnapshot(l,leagueKey));if(!legs.length)return{status:'open',result:null,pnl:0,legs,detail:'Awaiting wager details'};if(legs.some(l=>l.status==='loss'))return{status:'loss',result:'loss',pnl:-ticket.risk,legs,detail:'Ticket lost'};if(legs.every(l=>['win','push'].includes(l.status))){const hasPush=legs.some(l=>l.status==='push');const result=hasPush?'push':'win';return{status:result,result,pnl:result==='win'?ticket.toWin:0,legs,detail:result==='win'?'Ticket won':'Push'}}if(legs.some(l=>l.status==='live'))return{status:'live',result:null,pnl:0,legs,detail:'Live'};return{status:'open',result:null,pnl:0,legs,detail:'Upcoming'}}
function allTickets(league){return league.weeks.flatMap(w=>(w.tickets||[]).map(t=>({...t,week:w.week,weekLabel:w.label,weekObj:w})))}
function recordFrom(snaps){let w=0,l=0,p=0;snaps.forEach(s=>{if(s.result==='win')w++;else if(s.result==='loss')l++;else if(s.result==='push')p++});return{w,l,p,text:`${w}-${l}${p?'-'+p:''}`}}
function leagueStats(key){const league=DATA.leagues[key];const booked=allTickets(league).filter(t=>t.booked);const snaps=booked.map(t=>({t,s:ticketSnapshot(t,key)}));const risk=booked.reduce((a,t)=>a+Number(t.risk||0),0);const pnl=snaps.reduce((a,x)=>a+Number(x.s.pnl||0),0);const openRisk=snaps.filter(x=>['open','live'].includes(x.s.status)).reduce((a,x)=>a+Number(x.t.risk||0),0);const potential=snaps.filter(x=>['open','live'].includes(x.s.status)).reduce((a,x)=>a+Number(x.t.toWin||0),0);const rec=recordFrom(snaps.map(x=>x.s));return{risk,pnl,openRisk,potential,rec,roi:risk?100*pnl/risk:0,snaps}}
function weekStats(key,week){const tickets=(week.tickets||[]).filter(t=>t.booked);const snaps=tickets.map(t=>({t,s:ticketSnapshot(t,key)}));const risk=tickets.reduce((a,t)=>a+Number(t.risk||0),0);const settledRisk=snaps.filter(x=>['win','loss','push'].includes(x.s.status)).reduce((a,x)=>a+Number(x.t.risk||0),0);const openRisk=snaps.filter(x=>['open','live'].includes(x.s.status)).reduce((a,x)=>a+Number(x.t.risk||0),0);const potential=snaps.filter(x=>['open','live'].includes(x.s.status)).reduce((a,x)=>a+Number(x.t.toWin||0),0);const pnl=snaps.reduce((a,x)=>a+Number(x.s.pnl||0),0);const rec=recordFrom(snaps.map(x=>x.s));return{tickets,snaps,risk,settledRisk,openRisk,potential,pnl,rec,roi:risk?100*pnl/risk:0}}
function statusBadge(status){const labels={win:'WON',loss:'LOST',push:'PUSH',live:'LIVE',open:'UPCOMING',planned:'PLANNED',pass:'PASS'};return`<span class="badge ${esc(status)}">${labels[status]||esc(status)}</span>`}
function pnlClass(v){return v>0?'pos':v<0?'neg':'neu'}
function renderMetric(label,value,cls='neu'){return`<div class="metric"><div class="v ${cls}">${value}</div><div class="k">${label}</div></div>`}
function renderSummaries(){const keys=Object.keys(DATA.leagues);const stats=Object.fromEntries(keys.map(k=>[k,leagueStats(k)]));const risk=keys.reduce((a,k)=>a+stats[k].risk,0),pnl=keys.reduce((a,k)=>a+stats[k].pnl,0),openRisk=keys.reduce((a,k)=>a+stats[k].openRisk,0),potential=keys.reduce((a,k)=>a+stats[k].potential,0);const rec=recordFrom(keys.flatMap(k=>stats[k].snaps.map(x=>x.s)));$('#combinedSummary').innerHTML=`<div class="panel combined-card"><div><div class="combined-title">All Football</div><div class="combined-note">Combined view only; NCAA and NFL ledgers remain separate.</div></div>${renderMetric('Record',rec.text)}${renderMetric('Risked',unitFmt(risk))}${renderMetric('P/L',unitFmt(pnl),pnlClass(pnl))}${renderMetric('ROI',pct(risk?100*pnl/risk:0),pnlClass(pnl))}${renderMetric('Open Risk',unitFmt(openRisk))}${renderMetric('Profit Still Alive',money(potential),'pos')}</div>`;$('#leagueSummaries').innerHTML=keys.map(k=>{const s=stats[k];return`<div class="panel league-summary"><div class="league-name">${esc(DATA.leagues[k].label)}</div><div class="summary-row">${renderMetric('Record',s.rec.text)}${renderMetric('Risked',unitFmt(s.risk))}${renderMetric('P/L',unitFmt(s.pnl),pnlClass(s.pnl))}${renderMetric('ROI',pct(s.roi),pnlClass(s.pnl))}${renderMetric('Open Risk',unitFmt(s.openRisk))}${renderMetric('Profit Alive',money(s.potential),'pos')}</div></div>`}).join('')}
function liveSweatItems(){const items=[];Object.entries(DATA.leagues).forEach(([key,league])=>{allTickets(league).filter(t=>t.booked).forEach(t=>{const s=ticketSnapshot(t,key);if(s.status!=='live')return;if((t.legs||[]).length===1){const l=s.legs[0];items.push({key,t,s,title:t.description,detail:l.label,score:l.scoreText})}else{const finalWins=s.legs.filter(x=>x.status==='win').length,live=s.legs.filter(x=>x.status==='live').length,open=s.legs.filter(x=>x.status==='open').length;items.push({key,t,s,title:t.description,detail:`${finalWins}/${t.legs.length} legs won · ${live} live · ${open} upcoming`,score:s.legs.filter(x=>x.status==='live').map(x=>x.scoreText).join(' | ')})}})});return items}
function renderLiveSweat(){const items=liveSweatItems();if(!items.length){$('#liveSweat').innerHTML='';return}$('#liveSweat').innerHTML=`<div class="panel live-sweat-panel"><div class="section-title"><h2>🔥 Live Sweat</h2><div class="hint">Only tickets with games in progress appear here.</div></div><div class="live-grid">${items.map(x=>`<div class="sweat-card"><div class="sweat-top"><div><div class="sweat-cat">${esc(x.key)} · ${esc(x.t.category)}</div><div class="sweat-pick">${esc(x.title)}</div></div>${statusBadge('live')}</div><div class="sweat-detail">${esc(x.detail)}</div><div class="sweat-score">${esc(x.score||'Live')}</div></div>`).join('')}</div></div>`}
function gameExposure(key){const map=new Map();allTickets(DATA.leagues[key]).filter(t=>t.booked).forEach(t=>{const seen=new Set();(t.legs||[]).forEach(l=>{if(seen.has(l.gameKey))return;seen.add(l.gameKey);const g=map.get(l.gameKey)||{gameKey:l.gameKey,name:`${l.team} vs ${l.opponent}`,risk:0,tickets:0,eventId:l.espnEventId};g.risk+=Number(t.risk||0);g.tickets+=1;map.set(l.gameKey,g)})});return[...map.values()].sort((a,b)=>b.risk-a.risk)}
function renderExposure(){const html=Object.keys(DATA.leagues).map(key=>{const rows=gameExposure(key),max=Math.max(1,...rows.map(r=>r.risk));return`<div class="panel exposure-panel"><div class="section-title"><h3>${esc(key)} Game Exposure</h3><div class="hint">Ticket dollars affected by each game</div></div>${rows.length?`<div class="exposure-list">${rows.slice(0,8).map(r=>`<div class="exposure-row"><div><div class="exposure-name">${esc(r.name)}</div><div class="exposure-meta">${r.tickets} ticket${r.tickets===1?'':'s'} tied to this game</div></div><div class="exposure-bar"><span style="width:${Math.max(4,100*r.risk/max)}%"></span></div><div class="exposure-amt">${unitFmt(r.risk)}</div></div>`).join('')}</div>`:`<div class="empty">No booked wagers yet.</div>`}</div>`}).join('');$('#exposurePanels').innerHTML=`<div class="exposure-wrap">${html}</div>`}
function lineText(ticket){if(ticket.closingLine==null)return'—';const leg=(ticket.legs||[])[0];if(!leg||!['spread','total'].includes(leg.betType))return esc(String(ticket.closingLine));const booked=Number(leg.line),close=Number(ticket.closingLine);if(!Number.isFinite(booked)||!Number.isFinite(close))return'—';let clv;if(leg.betType==='spread')clv=booked-close;else clv=leg.direction==='under'?booked-close:close-booked;return`${esc(String(ticket.closingLine))} <span class="${pnlClass(clv)}">(${signed(clv)} CLV)</span>`}
function legDisplay(leg,snap){const type=leg.betType==='moneyline'?'ML':leg.betType==='spread'?`${leg.line>0?'+':''}${leg.line}`:`${String(leg.direction||'').toUpperCase()} ${leg.line}`;return`<div class="leg"><strong>${esc(leg.team)}</strong> ${esc(type)} vs ${esc(leg.opponent)} · ${snap?esc(snap.label):'—'}</div>`}
function ticketRows(key,week){const filter=state.filters[key]||'all';return(week.tickets||[]).filter(t=>{if(filter==='all')return true;const s=ticketSnapshot(t,key);if(filter==='live')return s.status==='live';if(filter==='upcoming')return['open','planned'].includes(s.status);if(filter==='settled')return['win','loss','push','pass'].includes(s.status);return true})}
function ticketDesktopRow(key,t){const s=ticketSnapshot(t,key);const pnl=s.status==='win'?t.toWin:s.status==='loss'?-t.risk:s.status==='push'?0:null;const legs=(t.legs||[]).map((l,i)=>legDisplay(l,s.legs?.[i])).join('');const liveInfo=(s.legs||[]).map(x=>x.scoreText).filter(Boolean).join('<br>');return`<tr><td><div class="category">${esc(t.category)}</div><div class="meta">${esc(t.betTypeGroup||'')}</div></td><td><div class="pick">${esc(t.description)}</div>${legs?`<div class="leglist meta">${legs}</div>`:''}</td><td class="stake">${t.booked?`${money(t.risk)}<div class="meta">${unitFmt(t.risk)}</div>`:'—'}</td><td class="money">${t.booked?`${money(t.toWin)}<div class="meta">${esc(t.odds||'')}</div>`:'—'}</td><td>${lineText(t)}</td><td>${statusBadge(s.status)}</td><td class="${pnl==null?'neu':pnlClass(pnl)} money">${pnl==null?'—':money(pnl)}</td><td><div class="small">${liveInfo||esc(s.detail||'—')}</div></td></tr>`}
function ticketMobileCard(key,t){const s=ticketSnapshot(t,key);const pnl=s.status==='win'?t.toWin:s.status==='loss'?-t.risk:s.status==='push'?0:null;return`<article class="bet-card"><div class="bet-card-head"><div><div class="sweat-cat">${esc(t.category)} · ${esc(t.betTypeGroup||'')}</div><div class="bet-card-pick">${esc(t.description)}</div></div>${statusBadge(s.status)}</div>${(t.legs||[]).length?`<div class="leglist meta">${(t.legs||[]).map((l,i)=>legDisplay(l,s.legs?.[i])).join('')}</div>`:''}<div class="bet-card-grid"><div><div class="k">Risk</div><div class="v">${t.booked?`${money(t.risk)} / ${unitFmt(t.risk)}`:'—'}</div></div><div><div class="k">To Win</div><div class="v">${t.booked?money(t.toWin):'—'}</div></div><div><div class="k">P/L</div><div class="v ${pnl==null?'neu':pnlClass(pnl)}">${pnl==null?'—':money(pnl)}</div></div><div><div class="k">Closing / CLV</div><div class="v">${lineText(t)}</div></div></div><div class="meta">${(s.legs||[]).map(x=>esc(x.scoreText)).filter(Boolean).join(' · ')||esc(s.detail||'')}</div></article>`}
function renderLeagueSections(){const out=[];Object.entries(DATA.leagues).forEach(([key,league])=>{if(state.selectedWeeks[key]==null)state.selectedWeeks[key]=league.weeks.at(-1)?.week||1;const week=league.weeks.find(w=>w.week===Number(state.selectedWeeks[key]))||league.weeks.at(-1);if(!week)return;const ws=weekStats(key,week),rows=ticketRows(key,week);const capRemain=Math.max(0,cap*unit-ws.risk),capPct=Math.min(100,100*ws.risk/(cap*unit));out.push(`<section class="league-section" data-league="${esc(key)}"><div class="league-header"><div class="league-title"><h2>${esc(league.label)}</h2><p>${esc(week.label)} · ${week.archived?'Archived final ledger':'Live ledger'}</p></div><div class="week-tools"><select class="week-select" data-league="${esc(key)}" aria-label="${esc(key)} week">${league.weeks.map(w=>`<option value="${w.week}" ${w.week===week.week?'selected':''}>${esc(w.label)}</option>`).join('')}</select><div class="filter-group">${['all','live','upcoming','settled'].map(f=>`<button type="button" class="filter-btn ${state.filters[key]===f?'active':''}" data-filter="${f}" data-league="${esc(key)}">${f[0].toUpperCase()+f.slice(1)}</button>`).join('')}</div></div></div><div class="week-strip"><div class="cell"><div class="label">Risked</div><div class="num">${unitFmt(ws.risk)}</div><div class="capbar"><span style="width:${capPct}%"></span></div></div><div class="cell"><div class="label">Settled Risk</div><div class="num">${unitFmt(ws.settledRisk)}</div></div><div class="cell"><div class="label">Open Risk</div><div class="num">${unitFmt(ws.openRisk)}</div></div><div class="cell"><div class="label">Profit Still Alive</div><div class="num pos">${money(ws.potential)}</div></div><div class="cell"><div class="label">Realized P/L</div><div class="num ${pnlClass(ws.pnl)}">${unitFmt(ws.pnl)}</div></div><div class="cell"><div class="label">Record</div><div class="num">${ws.rec.text}</div></div><div class="cell"><div class="label">ROI</div><div class="num ${pnlClass(ws.pnl)}">${pct(ws.roi)}</div></div><div class="cell"><div class="label">Cap Remaining</div><div class="num">${unitFmt(capRemain)}</div></div></div>${rows.length?`<div class="table-wrap"><table class="bets"><thead><tr><th>Category</th><th>Wager</th><th>Risk</th><th>To Win</th><th>Closing / CLV</th><th>Status</th><th>P/L</th><th>Live / Final</th></tr></thead><tbody>${rows.map(t=>ticketDesktopRow(key,t)).join('')}</tbody></table></div><div class="mobile-bets">${rows.map(t=>ticketMobileCard(key,t)).join('')}</div>`:`<div class="empty">No wagers match this filter.</div>`}${renderSeasonBlock(key,league)}</section>`)});$('#leagueSections').innerHTML=out.join('');document.querySelectorAll('.week-select').forEach(el=>el.addEventListener('change',e=>{state.selectedWeeks[e.target.dataset.league]=Number(e.target.value);renderAll()}));document.querySelectorAll('.filter-btn').forEach(el=>el.addEventListener('click',e=>{state.filters[e.currentTarget.dataset.league]=e.currentTarget.dataset.filter;renderAll()}))}
function weeklySeries(key,league){return league.weeks.map(w=>{const s=weekStats(key,w);return{week:w.week,label:w.label,pnl:s.pnl,risk:s.risk,roi:s.roi,record:s.rec.text}})}
function svgPnl(series){if(!series.length)return'<div class="empty">No weekly history yet.</div>';const w=600,h=160,pad=24;let cum=0;const vals=series.map(x=>{cum+=x.pnl;return cum});const min=Math.min(0,...vals),max=Math.max(0,...vals),span=Math.max(1,max-min);const x=i=>pad+(series.length===1?(w-2*pad)/2:i*(w-2*pad)/(series.length-1));const y=v=>h-pad-(v-min)*(h-2*pad)/span;const pts=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' '),zero=y(0);return`<svg class="pnl-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Cumulative profit and loss chart"><line class="axis" x1="${pad}" x2="${w-pad}" y1="${zero}" y2="${zero}"></line><polyline class="line" points="${pts}"></polyline>${vals.map((v,i)=>`<circle class="dotpoint" cx="${x(i)}" cy="${y(v)}" r="3"><title>${esc(series[i].label)}: ${money(v)}</title></circle>`).join('')}</svg>`}
function renderSeasonBlock(key,league){const series=weeklySeries(key,league);return`<div class="season"><div class="section-title"><h3>Season P/L</h3><div class="hint">Weekly results remain separate for ${esc(key)}</div></div><div class="season-grid"><div class="chart-card"><div class="chart-title">Cumulative Profit / Loss</div><div class="chart-sub">Archived results stay in the ledger even after the live score feed moves on.</div>${svgPnl(series)}</div><div class="stat-card"><table class="season-table"><thead><tr><th>Week</th><th>Record</th><th>Risk</th><th>P/L</th><th>ROI</th></tr></thead><tbody>${series.map(x=>`<tr><td>${esc(x.label)}</td><td>${x.record}</td><td>${unitFmt(x.risk)}</td><td class="${pnlClass(x.pnl)}">${unitFmt(x.pnl)}</td><td class="${pnlClass(x.pnl)}">${pct(x.roi)}</td></tr>`).join('')}</tbody></table></div></div></div>`}
function aggregateBy(key,field){const league=DATA.leagues[key],groups=new Map();allTickets(league).filter(t=>t.booked).forEach(t=>{const name=t[field]||'Other',s=ticketSnapshot(t,key);const g=groups.get(name)||{name,risk:0,pnl:0,w:0,l:0,p:0,count:0};g.risk+=Number(t.risk||0);g.pnl+=Number(s.pnl||0);g.count++;if(s.result==='win')g.w++;else if(s.result==='loss')g.l++;else if(s.result==='push')g.p++;groups.set(name,g)});return[...groups.values()].map(g=>({...g,roi:g.risk?100*g.pnl/g.risk:0})).sort((a,b)=>b.pnl-a.pnl)}
function leaderTable(rows){if(!rows.length)return'<div class="empty">No booked wagers yet.</div>';return`<table class="leader-table"><thead><tr><th>Group</th><th>Record</th><th>Risk</th><th>P/L</th><th>ROI</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.w}-${r.l}${r.p?'-'+r.p:''}</td><td>${unitFmt(r.risk)}</td><td class="${pnlClass(r.pnl)}">${unitFmt(r.pnl)}</td><td class="${pnlClass(r.pnl)}">${pct(r.roi)}</td></tr>`).join('')}</tbody></table>`}
function clvStats(key){const values=[];allTickets(DATA.leagues[key]).filter(t=>t.booked&&t.closingLine!=null&&(t.legs||[]).length===1).forEach(t=>{const l=t.legs[0];if(!['spread','total'].includes(l.betType))return;const booked=Number(l.line),close=Number(t.closingLine);if(!Number.isFinite(booked)||!Number.isFinite(close))return;const v=l.betType==='spread'?booked-close:(l.direction==='under'?booked-close:close-booked);values.push(v)});return{count:values.length,avg:values.length?values.reduce((a,b)=>a+b,0)/values.length:0,beat:values.filter(v=>v>0).length,tied:values.filter(v=>v===0).length,lost:values.filter(v=>v<0).length}}
function seasonExtremes(key){const series=weeklySeries(key,DATA.leagues[key]).filter(x=>x.risk>0);const best=series.length?[...series].sort((a,b)=>b.pnl-a.pnl)[0]:null,worst=series.length?[...series].sort((a,b)=>a.pnl-b.pnl)[0]:null;const settled=allTickets(DATA.leagues[key]).filter(t=>t.booked).map(t=>({t,s:ticketSnapshot(t,key)})).filter(x=>['win','loss','push'].includes(x.s.status));const bigWin=settled.filter(x=>x.s.pnl>0).sort((a,b)=>b.s.pnl-a.s.pnl)[0]||null,bigLoss=settled.filter(x=>x.s.pnl<0).sort((a,b)=>a.s.pnl-b.s.pnl)[0]||null;return{best,worst,bigWin,bigLoss}}
function renderAnalytics(){const blocks=Object.keys(DATA.leagues).map(key=>{const cat=aggregateBy(key,'category'),type=aggregateBy(key,'betTypeGroup'),clv=clvStats(key),ext=seasonExtremes(key);return`<div class="panel analytics-section"><div class="section-title"><h2>${esc(key)} Season Analytics</h2><div class="hint">Updates automatically as tickets settle.</div></div><div class="analytics-grid"><div class="analytics-card"><h3>Category Leaderboard</h3>${leaderTable(cat)}</div><div class="analytics-card"><h3>Bet-Type Leaderboard</h3>${leaderTable(type)}</div><div class="analytics-card"><h3>Closing Line Value</h3>${clv.count?`<div class="clv-summary"><div class="clv-box"><div class="v ${pnlClass(clv.avg)}">${signed(clv.avg)}</div><div class="k">Avg point CLV</div></div><div class="clv-box"><div class="v">${clv.beat}-${clv.lost}-${clv.tied}</div><div class="k">Beat-Lost-Tied close</div></div><div class="clv-box"><div class="v">${clv.count}</div><div class="k">Tracked closes</div></div></div>`:`<div class="empty">Closing lines have not been entered yet. Once a market closes, the tracker will show point CLV and whether we beat the close.</div>`}</div><div class="analytics-card"><h3>Season Highs / Lows</h3><table class="leader-table"><tbody><tr><td>Best week</td><td>${ext.best?`${esc(ext.best.label)} · ${unitFmt(ext.best.pnl)}`:'—'}</td></tr><tr><td>Worst week</td><td>${ext.worst?`${esc(ext.worst.label)} · ${unitFmt(ext.worst.pnl)}`:'—'}</td></tr><tr><td>Biggest win</td><td>${ext.bigWin?`${esc(ext.bigWin.t.category)} · ${money(ext.bigWin.s.pnl)}`:'—'}</td></tr><tr><td>Biggest loss</td><td>${ext.bigLoss?`${esc(ext.bigLoss.t.category)} · ${money(ext.bigLoss.s.pnl)}`:'—'}</td></tr></tbody></table></div></div></div>`}).join('');$('#analytics').innerHTML=blocks}
function uniqueGames(){const map=new Map();Object.entries(DATA.leagues).forEach(([key,league])=>{allTickets(league).forEach(t=>(t.legs||[]).forEach(l=>{if(!map.has(l.gameKey))map.set(l.gameKey,{...l,leagueKey:key})}))});return[...map.values()]}
function renderManual(){const rows=uniqueGames().map(g=>{const cur=state.overrides[g.gameKey]||{};return`<div class="override-grid" data-game="${esc(g.gameKey)}"><div><strong>${esc(g.team)} vs ${esc(g.opponent)}</strong><div class="small">${esc(g.leagueKey)} · ESPN ${esc(g.espnEventId||'fallback')}</div></div><input type="number" inputmode="numeric" data-field="teamScore" value="${cur.teams?.[0]?.score??''}" placeholder="${esc(g.team)}"><input type="number" inputmode="numeric" data-field="oppScore" value="${cur.teams?.[1]?.score??''}" placeholder="${esc(g.opponent)}"><select data-field="status"><option value="">No override</option><option value="scheduled" ${cur.status==='scheduled'?'selected':''}>Scheduled</option><option value="live" ${cur.status==='live'?'selected':''}>Live</option><option value="final" ${cur.status==='final'?'selected':''}>Final</option></select></div>`}).join('');$('#overrideRows').innerHTML=rows||'<div class="empty">No games loaded.</div>'}
function saveOverrides(){const next={...state.overrides};document.querySelectorAll('.override-grid').forEach(row=>{const gameKey=row.dataset.game,status=row.querySelector('[data-field="status"]').value;if(!status){delete next[gameKey];return}const game=uniqueGames().find(g=>g.gameKey===gameKey);const a=Number(row.querySelector('[data-field="teamScore"]').value||0),b=Number(row.querySelector('[data-field="oppScore"]').value||0);next[gameKey]={id:`manual-${gameKey}`,status,detail:'Manual override',date:null,teams:[{name:game.team,short:game.team,abbr:game.team,score:a,home:false},{name:game.opponent,short:game.opponent,abbr:game.opponent,score:b,home:true}]}});state.overrides=next;localStorage.setItem('football-score-overrides',JSON.stringify(next));$('#manualDialog').close();renderAll()}
function clearOverrides(){state.overrides={};localStorage.removeItem('football-score-overrides');renderManual();renderAll()}
async function fetchLeagueScores(key,league){const active=league.weeks.filter(w=>!w.archived&&w.dateStart&&w.dateEnd),weeks=active.length?active:(league.weeks.length?[league.weeks.at(-1)]:[]);if(!weeks.length){state.scores[key]=[];return}const extra=key==='NCAA'?'&groups=80&limit=1000':'&limit=100';const batches=await Promise.all(weeks.map(async w=>{const url=`https://site.api.espn.com/apis/site/v2/sports/football/${league.espnPath}/scoreboard?dates=${ymd(w.dateStart)}-${ymd(w.dateEnd)}${extra}`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`${key} ${res.status}`);const json=await res.json();return(json.events||[]).map(extractEvent).filter(Boolean)}));const dedup=new Map();batches.flat().forEach(ev=>dedup.set(String(ev.id),ev));state.scores[key]=[...dedup.values()]}
async function refreshScores(){$('#feedStatus').textContent='Refreshing public scores…';$('#liveDot').classList.remove('live');const results=await Promise.allSettled(Object.entries(DATA.leagues).map(([k,l])=>fetchLeagueScores(k,l))),failed=results.filter(x=>x.status==='rejected');state.lastRefresh=new Date();$('#lastRefresh').textContent=`Last refresh: ${formatStamp(state.lastRefresh.toISOString())}`;if(failed.length){$('#feedStatus').textContent=`Score feed partially available (${failed.length} league${failed.length>1?'s':''} failed)`}else{$('#feedStatus').textContent='Public score feed connected';$('#liveDot').classList.add('live')}renderAll()}
function exportResults(){const payload={exportedAt:new Date().toISOString(),build:CFG.build,leagues:{}};Object.entries(DATA.leagues).forEach(([key,league])=>{payload.leagues[key]=league.weeks.map(w=>({week:w.week,label:w.label,stats:weekStats(key,w),tickets:(w.tickets||[]).map(t=>({id:t.id,category:t.category,description:t.description,risk:t.risk,toWin:t.toWin,odds:t.odds,snapshot:ticketSnapshot(t,key)}))}))});const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`football-betting-results-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function renderAll(){renderSummaries();renderLiveSweat();renderExposure();renderLeagueSections();renderAnalytics();$('#siteUpdated').textContent=`Site updated: ${formatStamp(CFG.lastSiteUpdate)}`}
$('#refreshBtn').addEventListener('click',refreshScores);$('#manualBtn').addEventListener('click',()=>{renderManual();$('#manualDialog').showModal()});$('#closeManual').addEventListener('click',()=>$('#manualDialog').close());$('#saveOverrides').addEventListener('click',saveOverrides);$('#clearOverrides').addEventListener('click',clearOverrides);$('#exportBtn').addEventListener('click',exportResults);renderAll();refreshScores();setInterval(refreshScores,Math.max(30,Number(CFG.refreshSeconds)||60)*1000);
})();