(() => {
  const B=window.BT;if(!B)return;
  const {DATA,unit,cap,state,$,esc,money,unitFmt,pct,signed,ticketSnapshot,recordFrom,leagueStats,weekStats,performanceStats,gameExposure,weeklySeries,weekState}=B;
  const pnlClass=v=>v>0?'pos':v<0?'neg':'neu';
  const renderMetric=(label,value,cls='neu')=>`<div class="metric"><div class="v ${cls}">${value}</div><div class="k">${label}</div></div>`;
  const statusBadge=status=>{const labels={win:'WON',loss:'LOST',push:'PUSH',live:'LIVE',open:'UPCOMING',planned:'PLANNED',pass:'PASS',review:'REVIEW'};return`<span class="badge ${esc(status)}">${labels[status]||esc(status)}</span>`};
  function lineText(ticket){
    if(ticket.closingLine==null)return'—';const leg=(ticket.legs||[])[0];if(!leg||!['spread','total'].includes(leg.betType))return esc(String(ticket.closingLine));
    const booked=Number(leg.line),close=Number(ticket.closingLine);if(!Number.isFinite(booked)||!Number.isFinite(close))return'—';
    const clv=leg.betType==='spread'?booked-close:(leg.direction==='under'?booked-close:close-booked);return`${esc(String(ticket.closingLine))} <span class="${pnlClass(clv)}">(${signed(clv)} CLV)</span>`;
  }
  function legDisplay(leg,snap){
    const type=leg.betType==='moneyline'?'ML':leg.betType==='spread'?`${leg.line>0?'+':''}${leg.line}`:`${String(leg.direction||'').toUpperCase()} ${leg.line}`;
    return`<div class="leg"><strong>${esc(leg.team)}</strong> ${esc(type)} vs ${esc(leg.opponent)} · ${snap?esc(snap.label):'—'}</div>`;
  }
  function renderSummaries(){
    const keys=Object.keys(DATA.leagues),stats=Object.fromEntries(keys.map(k=>[k,leagueStats(k)]));
    const risk=keys.reduce((a,k)=>a+stats[k].risk,0),settledRisk=keys.reduce((a,k)=>a+stats[k].settledRisk,0),pnl=keys.reduce((a,k)=>a+stats[k].pnl,0),openRisk=keys.reduce((a,k)=>a+stats[k].openRisk+stats[k].reviewRisk,0),potential=keys.reduce((a,k)=>a+stats[k].potential,0),rec=recordFrom(keys.flatMap(k=>stats[k].snaps.map(x=>x.s)));
    $('#combinedSummary').innerHTML=`<div class="panel combined-card"><div><div class="combined-title">All Football</div><div class="combined-note">Combined view only; NCAA and NFL performance ledgers remain separate.</div></div>${renderMetric('Record',rec.text)}${renderMetric('Risked',unitFmt(risk))}${renderMetric('P/L',unitFmt(pnl),pnlClass(pnl))}${renderMetric('Realized ROI',pct(settledRisk?100*pnl/settledRisk:0),pnlClass(pnl))}${renderMetric('Open / Review Risk',unitFmt(openRisk))}${renderMetric('Profit Still Alive',money(potential),'pos')}</div>`;
    $('#leagueSummaries').innerHTML=keys.map(k=>{const s=stats[k];return`<div class="panel league-summary"><div class="league-name">${esc(DATA.leagues[k].label)}</div><div class="summary-row">${renderMetric('Record',s.rec.text)}${renderMetric('Risked',unitFmt(s.risk))}${renderMetric('P/L',unitFmt(s.pnl),pnlClass(s.pnl))}${renderMetric('Realized ROI',pct(s.roi),pnlClass(s.pnl))}${renderMetric('Open / Review Risk',unitFmt(s.openRisk+s.reviewRisk))}${renderMetric('Profit Alive',money(s.potential),'pos')}</div></div>`}).join('');
  }
  function renderPerformancePulse(){
    const rows=Object.keys(DATA.leagues).map(key=>{const p=performanceStats(key);return`<div class="pulse-league"><div class="pulse-name">${esc(DATA.leagues[key].label)}</div><div class="pulse-metrics">${renderMetric('Settled Bets',String(p.settled))}${renderMetric('Hit Rate',p.decisions?pct(p.hitRate):'—',p.hitRate>=55?'pos':'neu')}${renderMetric('Avg Stake',p.settled?unitFmt(p.avgStake):'—')}${renderMetric('Avg P/L / Bet',p.settled?unitFmt(p.avgPnl):'—',pnlClass(p.avgPnl))}${renderMetric('Current Streak',p.streak.current,p.streak.current.startsWith('W')?'pos':p.streak.current.startsWith('L')?'neg':'neu')}${renderMetric('Max Drawdown',p.settled?unitFmt(p.eq.maxDrawdown):'—','neg')}</div></div>`}).join('');
    $('#performancePulse').innerHTML=`<div class="panel performance-pulse"><div class="section-title"><h2>Season Pulse</h2><div class="hint">Realized metrics use settled wagers only.</div></div>${rows}</div>`;
  }
  function liveSweatItems(){
    const items=[];Object.entries(DATA.leagues).forEach(([key,league])=>{B.allTickets(league).filter(t=>t.booked).forEach(t=>{const s=ticketSnapshot(t,key);if(s.status!=='live')return;const won=s.legs.filter(x=>x.status==='win').length,live=s.legs.filter(x=>x.status==='live').length,open=s.legs.filter(x=>x.status==='open').length,total=(t.legs||[]).length;if(total===1){const l=s.legs[0];items.push({key,t,title:t.description,detail:l.label,score:l.scoreText,progress:null})}else items.push({key,t,title:t.description,detail:`${won}/${total} legs won · ${live} live · ${open} upcoming`,score:s.legs.filter(x=>x.status==='live').map(x=>x.scoreText).join(' | '),progress:100*(won+0.5*live)/Math.max(1,total)})})});return items;
  }
  function renderLiveSweat(){
    const items=liveSweatItems();if(!items.length){$('#liveSweat').innerHTML='';return}
    $('#liveSweat').innerHTML=`<div class="panel live-sweat-panel"><div class="section-title"><h2>🔥 Live Sweat</h2><div class="hint">Current edge, score and money still alive.</div></div><div class="live-grid">${items.map(x=>`<div class="sweat-card"><div class="sweat-top"><div><div class="sweat-cat">${esc(x.key)} · ${esc(x.t.category)}</div><div class="sweat-pick">${esc(x.title)}</div></div>${statusBadge('live')}</div><div class="sweat-detail">${esc(x.detail)}</div><div class="sweat-score">${esc(x.score||'Live')}</div>${x.progress!=null?`<div class="sweat-progress"><span style="width:${Math.max(4,Math.min(100,x.progress))}%"></span></div>`:''}<div class="sweat-money">Risk ${unitFmt(x.t.risk)} · To win <strong>${money(x.t.toWin)}</strong></div></div>`).join('')}</div></div>`;
  }
  function renderExposure(){
    const html=Object.keys(DATA.leagues).map(key=>{const rows=gameExposure(key),max=Math.max(1,...rows.map(r=>r.risk)),leagueRisk=Math.max(1,leagueStats(key).risk),top=rows[0];return`<div class="panel exposure-panel"><div class="section-title"><h3>${esc(key)} Game Exposure</h3><div class="hint">${top?`Top game touches ${pct(100*top.risk/leagueRisk)} of booked ticket risk`:'No exposure yet'}</div></div>${rows.length?`<div class="exposure-list">${rows.slice(0,10).map(r=>`<div class="exposure-row"><div><div class="exposure-name">${esc(r.name)}</div><div class="exposure-meta">${r.tickets} ticket${r.tickets===1?'':'s'} · ${pct(100*r.risk/leagueRisk)} of league ticket risk</div></div><div class="exposure-bar"><span style="width:${Math.max(4,100*r.risk/max)}%"></span></div><div class="exposure-amt">${unitFmt(r.risk)}</div></div>`).join('')}</div>`:`<div class="empty">No booked wagers yet.</div>`}</div>`}).join('');
    $('#exposurePanels').innerHTML=`<div class="exposure-wrap">${html}</div>`;
  }
  function ticketRows(key,week){
    const filter=state.filters[key]||'all';return(week.tickets||[]).filter(t=>{if(filter==='all')return true;const s=ticketSnapshot(t,key);if(filter==='live')return s.status==='live';if(filter==='upcoming')return['open','planned'].includes(s.status);if(filter==='settled')return['win','loss','push','pass'].includes(s.status);if(filter==='review')return s.status==='review';return true});
  }
  function ticketDesktopRow(key,t){
    const s=ticketSnapshot(t,key),pnl=['win','loss','push'].includes(s.status)?s.pnl:null,legs=(t.legs||[]).map((l,i)=>legDisplay(l,s.legs?.[i])).join(''),liveInfo=(s.legs||[]).map(x=>x.scoreText).filter(Boolean).join('<br>');
    return`<tr><td><div class="category">${esc(t.category)}</div><div class="meta">${esc(t.betTypeGroup||'')}</div></td><td><div class="pick">${esc(t.description)}</div>${legs?`<div class="leglist meta">${legs}</div>`:''}</td><td class="stake">${t.booked?`${money(t.risk)}<div class="meta">${unitFmt(t.risk)}</div>`:'—'}</td><td class="money">${t.booked?`${money(t.toWin)}<div class="meta">${esc(t.odds||'')}</div>`:'—'}</td><td>${lineText(t)}</td><td>${statusBadge(s.status)}${s.status==='review'?'<div class="meta">Confirm book rule</div>':''}</td><td class="${pnl==null?'neu':pnlClass(pnl)} money">${pnl==null?'—':money(pnl)}</td><td><div class="small">${liveInfo||esc(s.detail||'—')}</div></td></tr>`;
  }
  function ticketMobileCard(key,t){
    const s=ticketSnapshot(t,key),pnl=['win','loss','push'].includes(s.status)?s.pnl:null;
    return`<article class="bet-card"><div class="bet-card-head"><div><div class="sweat-cat">${esc(t.category)} · ${esc(t.betTypeGroup||'')}</div><div class="bet-card-pick">${esc(t.description)}</div></div>${statusBadge(s.status)}</div>${(t.legs||[]).length?`<div class="leglist meta">${(t.legs||[]).map((l,i)=>legDisplay(l,s.legs?.[i])).join('')}</div>`:''}<div class="bet-card-grid"><div><div class="k">Risk</div><div class="v">${t.booked?`${money(t.risk)} / ${unitFmt(t.risk)}`:'—'}</div></div><div><div class="k">To Win</div><div class="v">${t.booked?money(t.toWin):'—'}</div></div><div><div class="k">P/L</div><div class="v ${pnl==null?'neu':pnlClass(pnl)}">${pnl==null?'—':money(pnl)}</div></div><div><div class="k">Closing / CLV</div><div class="v">${lineText(t)}</div></div></div><div class="meta">${(s.legs||[]).map(x=>esc(x.scoreText)).filter(Boolean).join(' · ')||esc(s.detail||'')}</div>${s.status==='review'?'<div class="review-note">Push on multi-leg ticket — confirm BetWCS settlement before grading P/L.</div>':''}</article>`;
  }
  function svgPnl(series){
    if(!series.length)return'<div class="empty">No weekly history yet.</div>';const w=620,h=176,pad=28,vals=[0,...series.map(x=>x.cumulative)],min=Math.min(0,...vals),max=Math.max(0,...vals),span=Math.max(1,max-min),x=i=>pad+i*(w-2*pad)/Math.max(1,vals.length-1),y=v=>h-pad-(v-min)*(h-2*pad)/span,pts=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' '),zero=y(0);
    return`<svg class="pnl-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Cumulative profit and loss chart"><line class="axis" x1="${pad}" x2="${w-pad}" y1="${zero}" y2="${zero}"></line><polyline class="line" points="${pts}"></polyline>${vals.map((v,i)=>`<circle class="dotpoint" cx="${x(i)}" cy="${y(v)}" r="3"><title>${i===0?'Start':esc(series[i-1].label)}: ${unitFmt(v)}</title></circle>`).join('')}</svg>`;
  }
  function renderSeasonBlock(key,league){
    const series=weeklySeries(key,league),p=performanceStats(key),totalRisk=series.reduce((a,x)=>a+x.risk,0),active=series.filter(x=>x.risk>0).length,avgWeek=active?p.pnl/active:0;
    return`<div class="season"><div class="section-title"><h3>Season Ledger & Archive</h3><div class="hint">Completed weeks remain permanent after live scoring is archived.</div></div><div class="season-mini">${renderMetric('Season P/L',unitFmt(p.pnl),pnlClass(p.pnl))}${renderMetric('Total Risked',unitFmt(totalRisk))}${renderMetric('Avg P/L / Active Week',unitFmt(avgWeek),pnlClass(avgWeek))}${renderMetric('Peak P/L',unitFmt(p.eq.peak),pnlClass(p.eq.peak))}</div><div class="season-grid"><div class="chart-card"><div class="chart-title">Cumulative Profit / Loss</div><div class="chart-sub">Equity curve starts at 0u; this is profit tracking, not a bankroll assumption.</div>${svgPnl(series)}</div><div class="stat-card archive-scroll"><table class="season-table"><thead><tr><th>Week</th><th>State</th><th>Record</th><th>Risk</th><th>P/L</th><th>ROI</th><th>vs Prior</th></tr></thead><tbody>${series.map((x,i)=>`<tr><td>${esc(x.label)}</td><td><span class="archive-state">${esc(x.state)}</span></td><td>${x.record}</td><td>${unitFmt(x.risk)}</td><td class="${pnlClass(x.pnl)}">${unitFmt(x.pnl)}</td><td class="${pnlClass(x.pnl)}">${pct(x.roi)}</td><td class="${pnlClass(x.delta)}">${i===0?'—':unitFmt(x.delta)}</td></tr>`).join('')}</tbody></table></div></div></div>`;
  }
  function renderLeagueSections(){
    const out=[];Object.entries(DATA.leagues).forEach(([key,league])=>{
      if(state.selectedWeeks[key]==null)state.selectedWeeks[key]=league.weeks.at(-1)?.week||1;const week=league.weeks.find(w=>w.week===Number(state.selectedWeeks[key]))||league.weeks.at(-1);if(!week)return;
      const ws=weekStats(key,week),rows=ticketRows(key,week),capRemain=Math.max(0,cap*unit-ws.risk),capPct=Math.min(100,100*ws.risk/(cap*unit)),attention=ws.openRisk+ws.reviewRisk;
      out.push(`<section class="league-section" data-league="${esc(key)}"><div class="league-header"><div class="league-title"><h2>${esc(league.label)}</h2><p>${esc(week.label)} · ${esc(weekState(key,week))} ledger</p></div><div class="week-tools"><select class="week-select" data-league="${esc(key)}" aria-label="${esc(key)} week">${league.weeks.map(w=>`<option value="${w.week}" ${w.week===week.week?'selected':''}>${esc(w.label)}${w.archived?' · Archived':''}</option>`).join('')}</select><div class="filter-group">${['all','live','upcoming','settled','review'].map(f=>`<button type="button" class="filter-btn ${state.filters[key]===f?'active':''}" data-filter="${f}" data-league="${esc(key)}">${f[0].toUpperCase()+f.slice(1)}</button>`).join('')}</div></div></div><div class="week-strip"><div class="cell"><div class="label">Risked</div><div class="num">${unitFmt(ws.risk)}</div><div class="capbar"><span style="width:${capPct}%"></span></div></div><div class="cell"><div class="label">Settled Risk</div><div class="num">${unitFmt(ws.settledRisk)}</div></div><div class="cell"><div class="label">Open / Review Risk</div><div class="num">${unitFmt(attention)}</div></div><div class="cell"><div class="label">Profit Still Alive</div><div class="num pos">${money(ws.potential)}</div></div><div class="cell"><div class="label">Realized P/L</div><div class="num ${pnlClass(ws.pnl)}">${unitFmt(ws.pnl)}</div></div><div class="cell"><div class="label">Record</div><div class="num">${ws.rec.text}</div></div><div class="cell"><div class="label">Realized ROI</div><div class="num ${pnlClass(ws.pnl)}">${pct(ws.roi)}</div></div><div class="cell"><div class="label">Cap Remaining</div><div class="num">${unitFmt(capRemain)}</div></div></div>${rows.length?`<div class="table-wrap"><table class="bets"><thead><tr><th>Category</th><th>Wager</th><th>Risk</th><th>To Win</th><th>Closing / CLV</th><th>Status</th><th>P/L</th><th>Live / Final</th></tr></thead><tbody>${rows.map(t=>ticketDesktopRow(key,t)).join('')}</tbody></table></div><div class="mobile-bets">${rows.map(t=>ticketMobileCard(key,t)).join('')}</div>`:`<div class="empty">No wagers match this filter.</div>`}${renderSeasonBlock(key,league)}</section>`);
    });
    $('#leagueSections').innerHTML=out.join('');
    document.querySelectorAll('.week-select').forEach(el=>el.addEventListener('change',e=>{state.selectedWeeks[e.target.dataset.league]=Number(e.target.value);B.renderAll()}));
    document.querySelectorAll('.filter-btn').forEach(el=>el.addEventListener('click',e=>{state.filters[e.currentTarget.dataset.league]=e.currentTarget.dataset.filter;B.renderAll()}));
  }
  B.pnlClass=pnlClass;B.renderMetric=renderMetric;B.statusBadge=statusBadge;B.lineText=lineText;
  B.renderDashboard=()=>{renderSummaries();renderPerformancePulse();renderLiveSweat();renderExposure();renderLeagueSections()};
})();
